# Use a Node image to build and run the application
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json, package-lock.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the source code
COPY . .

# Expose port
EXPOSE 3000

# Run the Next.js development server
CMD ["npm", "run", "dev"]
