# Use the official Golang image as the base image
FROM golang:1.23-alpine

# Install Air for live reloading
RUN go install github.com/air-verse/air@latest

# Set the working directory
WORKDIR /app

# Copy the Go modules files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 8080

# Run the application with Air for live reloading
CMD ["air"]
